coverage:
  range: "80...100"

  status:
    project:
      default:
        threshold: 1
        paths:
          - "!src/routes/subRoutes/*"

    patch:
      default:
        branches:
          - master