proxy:
  image: kuzzleio/proxy:alpine
  ports:
    - "7511:7511"
    - "7512:7512"

backoffice:
  image: kuzzleio/bo-test:alpine
  command: /run-test.sh
  volumes:
    - "..:/var/app"
    - "./run-test.sh:/run-test.sh"
  ports:
    - "3000:3000"
  links:
    - proxy:kuzzle
    - kuzzle:main
    # add link to elasticsearch in order to perform a dump
    - elasticsearch
  environment:
    - DEBUG_PHANTOM
    - KUZZLE_URL
    - TRAVIS
    - TRAVIS_COMMIT
    - TRAVIS_JOB_NUMBER
    - TRAVIS_BRANCH
    - TRAVIS_JOB_ID
    - TRAVIS_PULL_REQUEST
    - TRAVIS_REPO_SLUG

kuzzle:
  image: kuzzleio/kuzzle:develop
  volumes:
    - "../kuzzle/fixtures.json:/fixtures.json"
  links:
    - elasticsearch
    - redis
    - proxy:api
  environment:
    - FIXTURES=/fixtures.json
    - FEATURE_COVERAGE

redis:
  image: redis:3.0-alpine

elasticsearch:
  image: kuzzleio/elasticsearch:2.2
