export const RECEIVE_INDEXES_COLLECTIONS = 'RECEIVE_INDEXES_COLLECTIONS'
export const ADD_STORED_COLLECTION = 'ADD_STORED_COLLECTION'
export const ADD_REALTIME_COLLECTION = 'ADD_REALTIME_COLLECTION'
export const ADD_INDEX = 'ADD_INDEX'

export const DELETE_INDEX = 'action/DELETE_INDEX'
export const LIST_INDEXES_AND_COLLECTION = 'action/LIST_INDEXES_AND_COLLECTION'
export const CREATE_INDEX = 'action/CREATE_INDEX'
