name: E2E Cypress tests
description: E2E tests using Cypress and different Kuzzle setup

inputs:
  backend_config:
    description: Kuzzle setup configuration (1 or 2 or multi)
    required: true
  CYPRESS_RECORD_KEY:
    description: Cypress token to record the tests on cypress dashboard
    required: true
  branch_name:
    description: Name of the branch to add a tag on cypress dashboard
    required: true

runs:
  using: "composite"
  steps:
    - run: npm ci --silent
      shell: bash
    - run: cd test/e2e/run-test && npm ci && cd -
      shell: bash
    - run: npm run test:e2e -- --backend=${{ inputs.backend_config}} --tag ${{ inputs.branch_name }}
      env:
        CYPRESS_RECORD_KEY: ${{ inputs.CYPRESS_RECORD_KEY }}
      shell: bash
