name: Lint
description: Run ESLint and the unreachable-modules check
runs:
  using: "composite"
  steps:
    - run: npm ci
      shell: bash

    - run: npm run test:lint
      shell: bash

    - run: npm run check:unreachable
      shell: bash
